### ISSUE TITLE
doesn't work on files with CRLF line endings

### ISSUE THREAD

**Issue by sobakasu** [experteer/simple_po_parser#2]
The error was:

    Failure/Error: raise PoSyntaxError.new(err_msg)

     SimplePoParser::ParserError:
       SimplePoParser::ParserErrorSyntax error in lines
       Syntax error in msgctxt
       Syntax error in msgid
       Syntax error in message_line
       There should be only whitespace until the end of line after the double quote character of a message text.
       Parseing result before error: '{}'
       SimplePoParser filtered backtrace: SimplePoParser::ParserError

The error went away after I converted the file to LF line endings.

**Comment by dfherr** [comment]
Sorry, I forgot about this.

This will be fixed.

**Comment by dfherr** [comment]
I released `1.1.5` which adds support for windows line ending encoded files. Performance drops by 50% using text mode, which enables the support for windows line endings. So to keep the performance for UNIX line ending files, which should be far more common for a GNU tool, I only activate textmode if a `CRLF` is found at the end of the first line.

The parser will continue to fail for files, which have `CRLF` on some line endings but not on the first.
